(defvar all-the-icons-data-alltheicons-alist '())

(defvar all-the-icons-data-alltheicons-compat-alist
  '(
    ("apache"            mfixx "apache")
    ("atom"              devopicons "atom")
    ("aws"               mfixx "aws")
    ("bower"             devopicons "bower")
    ("c"                 mfixx "c")
    ("c-line"            mfixx "c")
    ("clojure"           devopicons "clojure-alt")
    ("clojure-line"      devopicons "clojure")
    ("coffeescript"      devopicons "coffeescript")
    ("cplusplus"         mfixx "c++")
    ("cplusplus-line"    mfixx "c++")
    ("csharp"            mfixx "csharp")
    ("csharp-line"       mfixx "csharp")
    ("css3"              devopicons "css3")
    ("css3-alt"          devopicons "css3-full")
    ("d3"                file-icons "d3")
    ("dlang"             devopicons "dlang")
    ("elixir"            mfixx "elixir")
    ("erlang"            mfixx "erlang")
    ("git"               devopicons "git")
    ("go"                file-icons "go")
    ("google-drive"      devopicons "google-drive")
    ("grunt"             mfixx "grunt")
    ("grunt-line"        mfixx "grunt")
    ("gulp"              file-icons "gulp")
    ("haskell"           devopicons "haskell")
    ("html5"             devopicons "html5")
    ("jasmine"           file-icons "jasmine")
    ("java"              mfixx "java-bold")
    ("javascript"        mfixx "javascript")
    ("javascript-badge"  mfixx "javascript-alt")
    ("javascript-shield" devopicons "js-shield")
    ("less"              devopicons "less")
    ("nginx"             file-icons "nginx")
    ("nodejs"            mfixx "nodejs")
    ("perl"              mfixx "perl")
    ("perldocs"          devopicons "perl")
    ("postgresql"        mfixx "postgresql")
    ("prolog"            devopicons "prolog")
    ("python"            devopicons "python")
    ("react"             devopicons "react")
    ("ruby"              devopicons "ruby")
    ("ruby-alt"          devopicons "rub-rough")
    ("rust"              devopicons "rust")
    ("sass"              devopicons "sass")
    ("scala"             mfixx "scala")
    ("script"            mfixx "script")
    ("spring"            mfixx "spring")
    ("stylus"            devopicons "stylus")
    ("svg"               mfixx "svg")
    ("swift"             devopicons "swift")
    ("terminal"          devopicons "terminal-badge")
    ("terminal-alt"      devopicons "terminal")
    ("battery-charging"  fluentui-system-icons "battery_charge")

    ;; powerline symbols
    ;; ("arrow-left")
    ;; ("arrow-right")
    ;; ("cup-left")
    ;; ("cup-right")
    ;; ("slant-left")
    ;; ("slant-right")
    ;; ("wave-left")
    ;; ("wave-right")
    )
  )

(provide 'all-the-icons-data-alltheicons)
